package com.sf.biocapture.entity;
// Generated Jun 10, 2014 6:17:53 PM by Hibernate Tools 4.0.0

//import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.sf.biocapture.entity.base.BaseEntity;

/**
 * DuplicateNode generated by hbm2java
 */
@Entity
@Table(name = "DUPLICATE_NODE")
public class DuplicateNode extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3061119047317985952L;


	@Column(name = "TAG_NAME")
	private String tagName;

	
	@Column(name = "MAC_ADDRESS")
	private String macAddress;
	
	@Column(name = "INTALLATION_TIMESTAMP")
	private Timestamp intallationTimestamp;
	
	@Column(name = "INSTALLED_BY")
	private String installedBy;
	
	@Column(name = "NETWORK_CARD_NAME")
	private String networkCardName;

	public DuplicateNode() {
		
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}
	public String getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}
	public Timestamp getIntallationTimestamp() {
		return this.intallationTimestamp;
	}

	public void setIntallationTimestamp(Timestamp intallationTimestamp) {
		this.intallationTimestamp = intallationTimestamp;
	}
	public String getInstalledBy() {
		return this.installedBy;
	}

	public void setInstalledBy(String installedBy) {
		this.installedBy = installedBy;
	}
	public String getNetworkCardName() {
		return this.networkCardName;
	}

	public void setNetworkCardName(String networkCardName) {
		this.networkCardName = networkCardName;
	}

}
