package com.sf.biocapture.entity;
// Generated Jun 10, 2014 6:17:53 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sf.biocapture.entity.base.BaseEntity;

/**
 * HeartBeat generated by hbm2java
 */
@Entity
@Table(name = "HEART_BEAT")
public class HeartBeat extends BaseEntity {

    private static final long serialVersionUID = 2209898864458919730L;

    @Column(name = "TAG")
    private String tag;

    @Column(name = "AGENT_NAME")
    private String agentName;

    @Column(name = "AGENT_MOBILE")
    private String agentMobile;

    @Column(name = "MAC_ADDRESS")
    private String macAddress;

    @Column(name = "DEPLOY_STATE")
    private String deployState;

    @Column(name = "CAMERA_STATUS")
    private String cameraStatus;

    @Column(name = "SCANNER_STATUS")
    private String scannerStatus;

    @Column(name = "CLIENT_TIME_STATUS")
    private String clientTimeStatus;

    @Column(name = "CLIENT_UPTIME")
    private Long clientUptime;

    @Column(name = "RECEIPT_TIMESTAMP", nullable = false)
    private Timestamp receiptTimestamp;

    @Column(name = "LONGITUDE")
    private Double longitude;

    @Column(name = "LATITUDE")
    private Double latitude;

    @Column(name = "MODEM_SERIAL")
    private String modemSerial;

    @Column(name = "MODEM_MODEL")
    private String modemModel;

    @Column(name = "MODEM_SIGNAL_LEVEL")
    private String modemSignalLevel;

    @Column(name = "LOGIN_UPTIME")
    private Long loginUptime;

    @Column(name = "TOTAL_REGISTERED")
    private Long totalRegistered;

    @Column(name = "TOTAL_SENT")
    private Long totalSent;

    @Column(name = "TOTAL_CONFIRMED")
    private Long totalConfirmed;

    @Column(name = "DAILY_REGISTERED")
    private Long dailyRegistered;

    @Column(name = "DAILY_SENT")
    private Long dailySent;

    @Column(name = "DAILY_CONFIRMED")
    private Long dailyConfirmed;

    @Column(name = "APP_VERSION")
    private String appVersion;

    @Column(name = "THRESHOLD_VERSION")
    private String thresholdVersion;

    @Column(name = "REF_DEVICE_ID")
    private String refDeviceId;

    @Column(name = "REALTIME_DEVICE_ID")
    private String realTimeDeviceId;

    @Column(name = "NETWORK_STRENGTH")
    private String networkStrength;

    @Column(name = "NETWORK_CONNECTION_TYPE")
    private String networkConnectionType;

    @Column(name = "NETWORK_TYPE")
    private String networkType;

    @Column(name = "ROOTED")
    private Boolean rooted;

    @Column(name = "OS_NAME")
    private String osName;

    @Column(name = "OS_VERSION")
    private String osVersion;

    @Column(name = "LOCATION_INFORMATION_SOURCE")
    private String locationInformationSource;

    @Column(name = "LOCATION_ACCURACY")
    private Double locationAccuracy;

    @Column(name = "PROCESSOR_SPEED")
    private String processorSpeed;

    @Column(name = "USED_STORAGE")
    private String usedStorage;

    @Column(name = "AVAILABLE_STORAGE")
    private String availableStorage;

    @Column(name = "TOTAL_STORAGE")
    private String totalStorage;

    @Column(name = "RAM_SIZE")
    private String ramSize;

    @Column(name = "MOCKED_COORDINATE")
    private Boolean mockedCoordinate;
    
    @Column(name = "PHONE_STATUS_ENABLED")
    private Boolean phoneStatusEnabled;
   
    @Column(name = "LOCATION_PERMISSION_GRANTED")
    private Boolean locationPermissionGranted;
    
    @Column(name = "LOCATION_GENERATION_TIME")
    private Date locationGenerationTime;

    @Column(name = "LIVENESS_THRESHOLD_VERSION")
    private String livenessThresholdVersion;

    @Column(name = "CLIENT_TIMESTAMP")
    @Temporal(TemporalType.TIMESTAMP)
    private Date clientTime;
    
    @Column(name = "PING_LATENCY")
    private Long pingLatency;
    
    @Column(name = "SERVER_RESPONSE_TIME")
    private Timestamp responseTime;
    
    @Column(name = "DISPLAY_INCORRECT_TIME")
    private Boolean displayIncorrectTime;//current setting value for displayIncorrectTime setting
    
    @Column(name = "AGENT_EMAIL")
    private String agentEmail;

    public HeartBeat() {

    }

    public Date getClientTime() {
		return clientTime;
	}

	public void setClientTime(Date clientTime) {
		this.clientTime = clientTime;
	}

	public String getLivenessThresholdVersion() {
		return livenessThresholdVersion;
	}

	public void setLivenessThresholdVersion(String livenessThresholdVersion) {
		this.livenessThresholdVersion = livenessThresholdVersion;
	}

	public String getAppVersion() {
        return appVersion;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    public String getTag() {
        return this.tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getAgentName() {
        return this.agentName;
    }

    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }

    public String getAgentMobile() {
        return this.agentMobile;
    }

    public void setAgentMobile(String agentMobile) {
        this.agentMobile = agentMobile;
    }

    public String getMacAddress() {
        return this.macAddress;
    }

    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    public String getDeployState() {
        return this.deployState;
    }

    public void setDeployState(String deployState) {
        this.deployState = deployState;
    }

    public String getCameraStatus() {
        return this.cameraStatus;
    }

    public void setCameraStatus(String cameraStatus) {
        this.cameraStatus = cameraStatus;
    }

    public String getScannerStatus() {
        return this.scannerStatus;
    }

    public void setScannerStatus(String scannerStatus) {
        this.scannerStatus = scannerStatus;
    }

    public String getClientTimeStatus() {
        return this.clientTimeStatus;
    }

    public void setClientTimeStatus(String clientTimeStatus) {
        this.clientTimeStatus = clientTimeStatus;
    }

    public Long getClientUptime() {
        return this.clientUptime;
    }

    public void setClientUptime(Long clientUptime) {
        this.clientUptime = clientUptime;
    }

    public Timestamp getReceiptTimestamp() {
        return this.receiptTimestamp;
    }

    public void setReceiptTimestamp(Timestamp receiptTimestamp) {
        this.receiptTimestamp = receiptTimestamp;
    }

    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public String getModemSerial() {
        return this.modemSerial;
    }

    public void setModemSerial(String modemSerial) {
        this.modemSerial = modemSerial;
    }

    public String getModemModel() {
        return this.modemModel;
    }

    public void setModemModel(String modemModel) {
        this.modemModel = modemModel;
    }

    public String getModemSignalLevel() {
        return this.modemSignalLevel;
    }

    public void setModemSignalLevel(String modemSignalLevel) {
        this.modemSignalLevel = modemSignalLevel;
    }

    public Long getLoginUptime() {
        return this.loginUptime;
    }

    public void setLoginUptime(Long loginUptime) {
        this.loginUptime = loginUptime;
    }

    public Long getTotalRegistered() {
        return this.totalRegistered;
    }

    public void setTotalRegistered(Long totalRegistered) {
        this.totalRegistered = totalRegistered;
    }

    public Long getTotalSent() {
        return this.totalSent;
    }

    public void setTotalSent(Long totalSent) {
        this.totalSent = totalSent;
    }

    public Long getTotalConfirmed() {
        return this.totalConfirmed;
    }

    public void setTotalConfirmed(Long totalConfirmed) {
        this.totalConfirmed = totalConfirmed;
    }

    public Long getDailyRegistered() {
        return this.dailyRegistered;
    }

    public void setDailyRegistered(Long dailyRegistered) {
        this.dailyRegistered = dailyRegistered;
    }

    public Long getDailySent() {
        return this.dailySent;
    }

    public void setDailySent(Long dailySent) {
        this.dailySent = dailySent;
    }

    public Long getDailyConfirmed() {
        return this.dailyConfirmed;
    }

    public void setDailyConfirmed(Long dailyConfirmed) {
        this.dailyConfirmed = dailyConfirmed;
    }

    public String getThresholdVersion() {
        return thresholdVersion;
    }

    public void setThresholdVersion(String thresholdVersion) {
        this.thresholdVersion = thresholdVersion;
    }

    public String getRefDeviceId() {
        return refDeviceId;
    }

    public void setRefDeviceId(String refDeviceId) {
        this.refDeviceId = refDeviceId;
    }

    public String getRealTimeDeviceId() {
        return realTimeDeviceId;
    }

    public void setRealTimeDeviceId(String realTimeDeviceId) {
        this.realTimeDeviceId = realTimeDeviceId;
    }

    public String getNetworkStrength() {
        return networkStrength;
    }

    public void setNetworkStrength(String networkStrength) {
        this.networkStrength = networkStrength;
    }

    public String getNetworkConnectionType() {
        return networkConnectionType;
    }

    public void setNetworkConnectionType(String networkConnectionType) {
        this.networkConnectionType = networkConnectionType;
    }

    public Boolean getRooted() {
        return rooted;
    }

    public void setRooted(Boolean rooted) {
        this.rooted = rooted;
    }

    public String getOsName() {
        return osName;
    }

    public void setOsName(String osName) {
        this.osName = osName;
    }

    public String getOsVersion() {
        return osVersion;
    }

    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    public String getLocationInformationSource() {
        return locationInformationSource;
    }

    public void setLocationInformationSource(String locationInformationSource) {
        this.locationInformationSource = locationInformationSource;
    }

    public Double getLocationAccuracy() {
        return locationAccuracy;
    }

    public void setLocationAccuracy(Double locationAccuracy) {
        this.locationAccuracy = locationAccuracy;
    }

    public String getProcessorSpeed() {
        return processorSpeed;
    }

    public void setProcessorSpeed(String processorSpeed) {
        this.processorSpeed = processorSpeed;
    }

    public String getUsedStorage() {
        return usedStorage;
    }

    public void setUsedStorage(String usedStorage) {
        this.usedStorage = usedStorage;
    }

    public String getAvailableStorage() {
        return availableStorage;
    }

    public void setAvailableStorage(String availableStorage) {
        this.availableStorage = availableStorage;
    }

    public String getTotalStorage() {
        return totalStorage;
    }

    public void setTotalStorage(String totalStorage) {
        this.totalStorage = totalStorage;
    }

    public String getRamSize() {
        return ramSize;
    }

    public void setRamSize(String ramSize) {
        this.ramSize = ramSize;
    }

    public String getNetworkType() {
        return networkType;
    }

    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }

    public Boolean getMockedCoordinate() {
        return mockedCoordinate;
    }

    public void setMockedCoordinate(Boolean mockedCoordinate) {
        this.mockedCoordinate = mockedCoordinate;
    }

	public Boolean getPhoneStatusEnabled() {
		return phoneStatusEnabled;
	}

	public void setPhoneStatusEnabled(Boolean phoneStatusEnabled) {
		this.phoneStatusEnabled = phoneStatusEnabled;
	}

	public Boolean getLocationPermissionGranted() {
		return locationPermissionGranted;
	}

	public void setLocationPermissionGranted(Boolean locationPermissionGranted) {
		this.locationPermissionGranted = locationPermissionGranted;
	}

	public Date getLocationGenerationTime() {
		return locationGenerationTime;
	}

	public void setLocationGenerationTime(Date locationGenerationTime) {
		this.locationGenerationTime = locationGenerationTime;
	}

	public long getPingLatency() {
		return pingLatency;
	}

	public void setPingLatency(long pingLatency) {
		this.pingLatency = pingLatency;
	}

	public Timestamp getResponseTime() {
		return responseTime;
	}

	public void setResponseTime(Timestamp responseTime) {
		this.responseTime = responseTime;
	}

	public Boolean getDisplayIncorrectTime() {
		return displayIncorrectTime;
	}

	public void setDisplayIncorrectTime(Boolean displayIncorrectTime) {
		this.displayIncorrectTime = displayIncorrectTime;
	}

	public String getAgentEmail() {
		return agentEmail;
	}

	public void setAgentEmail(String agentEmail) {
		this.agentEmail = agentEmail;
	}

}
